# Generated by Django 2.1.7 on 2019-03-29 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_hospital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='find_hosp',
            name='created_at',
        ),
    ]
