# Generated by Django 2.1.7 on 2019-03-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_hospital', '0003_auto_20190330_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='find_hosp',
            name='contact',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='find_hosp',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='find_hosp',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
