# Generated by Django 2.1.7 on 2019-03-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_hospital', '0004_auto_20190330_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='find_hosp',
            name='contact',
            field=models.CharField(max_length=20),
        ),
    ]
